######################################################################
# Automatically generated by qmake (2.01a) Tue May 8 21:43:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += tut_5.cpp
