######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 8 13:38:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age_app.cpp
