######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 4 10:33:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
