######################################################################
# Automatically generated by qmake (2.01a) Tue May 8 22:00:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += tut_6.cpp
