######################################################################
# Automatically generated by qmake (2.01a) Tue May 22 20:52:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
