######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 4 10:28:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_2.cpp
