######################################################################
# Automatically generated by qmake (2.01a) Tue May 8 06:00:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
