######################################################################
# Automatically generated by qmake (2.01a) Wed May 9 07:24:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h lcdrange.h
SOURCES += cannonfield.cpp lcdrange.cpp main.cpp
